CREATE TABLE `PRINCIPAL` (
  `ID` bigint(20) NOT NULL,
  `CREATION_DATE` datetime NOT NULL,
  `ISINDIVIDUAL` bit(1) NOT NULL,
  `PRINCIPAL_NAME_LOWER` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `PRINCIPAL_NAME_DISPLAY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `MUST_PROVIDE_NEW_PRICIPAL_NAME` bit(1) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `EMAIL` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PRINCIPAL_LWR_UNIQUE` (`PRINCIPAL_NAME_LOWER`),
  UNIQUE KEY `PRINCIPAL_DIS_UNIQUE` (`PRINCIPAL_NAME_DISPLAY`),
  UNIQUE KEY `PRINCIPAL_EMAIL_UNIQUE` (`EMAIL`)
)