CREATE TABLE IF NOT EXISTS `REALM_PRINCIPAL` (
  `ID` BIGINT NOT NULL,
  `REALM` BIGINT NOT NULL,
  `PRINCIPAL` BIGINT NOT NULL,
  `TYPE` ENUM('ANONYMOUS', 'PUBLIC', 'AUTHENTICATED', 'ADMINISTRATORS') NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`PRINCIPAL`),
  UNIQUE (`REALM`, `TYPE`),
  CONSTRAINT `REALM_PRINCIPAL_REALM_FK` FOREIGN KEY (`REALM_ID`) REFERENCES `REALM` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `PRINCIPAL_FK` FOREIGN KEY (`PRINCIPAL`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
)
