CREATE TABLE IF NOT EXISTS `IDP` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `NAME` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `ANONYMOUS` BIGINT,
  `PUBLIC` BIGINT,
  `AUTHENTICATED` BIGINT,
  `ADIMINSTRATOR` BIGINT,
  PRIMARY KEY (`ID`),
  UNIQUE (`NAME`),
  CONSTRAINT `ANONYMOUS_FK` FOREIGN KEY (`ANONYMOUS`) REFERENCES `USER_GROUP` (`ID`) ON DELETE SET NULL,
  CONSTRAINT `PUBLIC_FK` FOREIGN KEY (`PUBLIC`) REFERENCES `USER_GROUP` (`ID`) ON DELETE SET NULL,
  CONSTRAINT `AUTHENTICATED_FK` FOREIGN KEY (`AUTHENTICATED`) REFERENCES `USER_GROUP` (`ID`) ON DELETE SET NULL,
  CONSTRAINT `ADIMINSTRATOR_FK` FOREIGN KEY (`ADIMINSTRATOR`) REFERENCES `USER_GROUP` (`ID`) ON DELETE SET NULL
)
