CREATE TABLE IF NOT EXISTS `REALM_IDP` (
  `REALM_ID` BIGINT NOT NULL,
  `PROVIDER` ENUM('SYNAPSE', 'GOOGLE_OAUTH_2_0', 'ORCID', 'ARCUS_BIOSCIENCES') NOT NULL,
  PRIMARY KEY (`REALM_ID`, `PROVIDER`),
  UNIQUE (`PROVIDER`)
)
