CREATE TABLE IF NOT EXISTS `SEARCH_CONFIGURATION` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ORGANIZATION_NAME` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `DEFAULT_ANALYZER_ID` BIGINT DEFAULT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SC_ORG_NAME` (`ORGANIZATION_NAME`, `NAME`),
  CONSTRAINT `SC_ORG_FK` FOREIGN KEY (`ORGANIZATION_NAME`) REFERENCES `ORGANIZATION` (`NAME`) ON DELETE RESTRICT,
  CONSTRAINT `SC_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `SC_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `SC_DEFAULT_ANALYZER_FK` FOREIGN KEY (`DEFAULT_ANALYZER_ID`) REFERENCES `TEXT_ANALYZER` (`ID`) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `SEARCH_CONFIG_SYNONYM_SET` (
  `CONFIG_ID` BIGINT NOT NULL,
  `SYNONYM_SET_ID` BIGINT NOT NULL,
  PRIMARY KEY (`CONFIG_ID`, `SYNONYM_SET_ID`),
  CONSTRAINT `SC_SS_CONFIG_FK` FOREIGN KEY (`CONFIG_ID`) REFERENCES `SEARCH_CONFIGURATION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `SC_SS_SYNSET_FK` FOREIGN KEY (`SYNONYM_SET_ID`) REFERENCES `SYNONYM_SET` (`ID`) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `SEARCH_CONFIG_COL_ANALYZER` (
  `CONFIG_ID` BIGINT NOT NULL,
  `COLUMN_ANALYZER_OVERRIDE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`CONFIG_ID`, `COLUMN_ANALYZER_OVERRIDE_ID`),
  CONSTRAINT `SC_CA_CONFIG_FK` FOREIGN KEY (`CONFIG_ID`) REFERENCES `SEARCH_CONFIGURATION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `SC_CA_OVERRIDE_FK` FOREIGN KEY (`COLUMN_ANALYZER_OVERRIDE_ID`) REFERENCES `COLUMN_ANALYZER_OVERRIDE` (`ID`) ON DELETE RESTRICT
);
