CREATE TABLE IF NOT EXISTS `SEARCH_CONFIG_SYNONYM_SET` (
  `CONFIG_ID` BIGINT NOT NULL,
  `ORDINAL` INT NOT NULL,
  `SYNONYM_SET_ID` BIGINT NOT NULL,
  PRIMARY KEY (`CONFIG_ID`, `ORDINAL`),
  UNIQUE KEY `SC_SS_CONFIG_SYNSET_UK` (`CONFIG_ID`, `SYNONYM_SET_ID`),
  CONSTRAINT `SC_SS_CONFIG_FK` FOREIGN KEY (`CONFIG_ID`) REFERENCES `SEARCH_CONFIGURATION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `SC_SS_SYNSET_FK` FOREIGN KEY (`SYNONYM_SET_ID`) REFERENCES `SYNONYM_SET` (`ID`) ON DELETE RESTRICT
);
