CREATE TABLE IF NOT EXISTS `SEARCH_INDEX_SOURCE_TABLE` (
  `SEARCH_INDEX_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `SOURCE_TABLE_ID` BIGINT NOT NULL,
  `SOURCE_TABLE_VERSION` BIGINT NOT NULL,
  PRIMARY KEY (`SEARCH_INDEX_ID`),
  KEY `SEARCH_INDEX_SOURCE_IDX` (`SOURCE_TABLE_ID`, `SOURCE_TABLE_VERSION`),
  CONSTRAINT `SEARCH_INDEX_SOURCE_NODE_FK` FOREIGN KEY (`SEARCH_INDEX_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)
