CREATE TABLE IF NOT EXISTS `SEARCH_CONFIG_COL_ANALYZER` (
  `CONFIG_ID` BIGINT NOT NULL,
  `COLUMN_ANALYZER_OVERRIDE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`CONFIG_ID`, `COLUMN_ANALYZER_OVERRIDE_ID`),
  CONSTRAINT `SC_CA_CONFIG_FK` FOREIGN KEY (`CONFIG_ID`) REFERENCES `SEARCH_CONFIGURATION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `SC_CA_OVERRIDE_FK` FOREIGN KEY (`COLUMN_ANALYZER_OVERRIDE_ID`) REFERENCES `COLUMN_ANALYZER_OVERRIDE` (`ID`) ON DELETE RESTRICT
);
