CREATE TABLE IF NOT EXISTS `TEXT_ANALYZER` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `ORGANIZATION_ID` BIGINT DEFAULT NULL,
  `SETTINGS` JSON NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_TA_ORG_NAME` (`ORGANIZATION_ID`, `NAME`),
  CONSTRAINT `TA_ORG_FK` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `TA_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `TA_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
)
