CREATE TABLE IF NOT EXISTS `USER_GROUP` (
  `ID` BIGINT NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `ISINDIVIDUAL` bit(1) DEFAULT NULL,
  `ETAG` char(36) NOT NULL DEFAULT '0',
  `REALM` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `REALM_FK` FOREIGN KEY (`REALM`) REFERENCES `REALM` (`ID`) ON DELETE RESTRICT
)
