CREATE TABLE `PROJECT_STORAGE_LIMIT` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP NOT NULL,
  `PROJECT_ID` BIGINT NOT NULL,
  `STORAGE_LOCATION_ID` BIGINT NOT NULL,
  `MAX_BYTES` BIGINT DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE(`PROJECT_ID`, `STORAGE_LOCATION_ID`),
  CONSTRAINT `PROJECT_STORAGE_LIMIT_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `PROJECT_STORAGE_LIMIT_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `PROJECT_STORAGE_LIMIT_PROJECT_ID_FK` FOREIGN KEY (`PROJECT_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `PROJECT_STORAGE_LIMIT_STORAGE_LOCATION_ID_FK` FOREIGN KEY (`STORAGE_LOCATION_ID`) REFERENCES `STORAGE_LOCATION` (`ID`) ON DELETE CASCADE
);