WITH LATEST_SNAP AS (
  SELECT s.SESSION_ID, s.CREATED_ON AS LATEST_SNAPSHOT_ON, s.CLOCK_TABLE
  FROM GRID_SNAPSHOT s
  INNER JOIN (
    SELECT SESSION_ID, MAX(CREATED_ON) AS MAX_CREATED_ON
    FROM GRID_SNAPSHOT
    GROUP BY SESSION_ID
  ) latest ON latest.SESSION_ID = s.SESSION_ID AND s.CREATED_ON = latest.MAX_CREATED_ON
)
SELECT gs.SESSION_ID
FROM GRID_SESSION gs
INNER JOIN GRID_CONNECTION gc
  ON gc.SESSION_ID = gs.SESSION_ID AND gc.SOURCE = 'INTERNAL'
LEFT JOIN LATEST_SNAP snap
  ON snap.SESSION_ID = gs.SESSION_ID
LEFT JOIN (
  SELECT gp.SESSION_ID, COUNT(*) AS PATCH_COUNT, MIN(gp.CREATED_ON) AS OLDEST_PATCH_ON
  FROM GRID_PATCH gp
  LEFT JOIN LATEST_SNAP ls
    ON ls.SESSION_ID = gp.SESSION_ID
  LEFT JOIN JSON_TABLE(
    IFNULL(ls.CLOCK_TABLE, JSON_ARRAY()), '$[*]' COLUMNS (
      REPLICA_ID BIGINT PATH '$[0]',
      SEQUENCE_NUMBER BIGINT PATH '$[1]'
    )
  ) ct ON ct.REPLICA_ID = gp.PATCH_ID_REP
  WHERE ls.SESSION_ID IS NULL
    OR ct.REPLICA_ID IS NULL
    OR gp.PATCH_ID_SEQ > ct.SEQUENCE_NUMBER
  GROUP BY gp.SESSION_ID
) pc ON pc.SESSION_ID = gs.SESSION_ID
WHERE
  pc.PATCH_COUNT > 0
  AND (
    snap.LATEST_SNAPSHOT_ON IS NULL
    OR pc.OLDEST_PATCH_ON < NOW() - INTERVAL ? SECOND
    OR pc.PATCH_COUNT > ?
  )
GROUP BY gs.SESSION_ID
ORDER BY snap.LATEST_SNAPSHOT_ON ASC
LIMIT ?
