CREATE TABLE IF NOT EXISTS GRID_REPLICA_OBJ (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    OBJ_REP BIGINT NOT NULL,
	OBJ_SEQ BIGINT NOT NULL,
	OBJ_VAL JSON NOT NULL,
	ROW_VEC_REP BIGINT AS (OBJ_VAL->>'$.data[0]'),
	ROW_VEC_SEQ BIGINT AS (OBJ_VAL->>'$.data[1]'),
	META_OBJ_REP BIGINT AS (OBJ_VAL->>'$.metadata[0]'),
	META_OBJ_SEQ BIGINT AS (OBJ_VAL->>'$.metadata[1]'),
	PRIMARY KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ),
	INDEX ROW_VEC_IDX(SESSION_ID, REPLICA_ID, ROW_VEC_REP, ROW_VEC_SEQ),
	INDEX META_OBJ_IDX(SESSION_ID, REPLICA_ID, META_OBJ_REP, META_OBJ_SEQ),
   CONSTRAINT `GRID_OBJ_REPLICA_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);