CREATE TABLE IF NOT EXISTS GRID_OBJ (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    OBJ_REP BIGINT NOT NULL,
	OBJ_SEQ BIGINT NOT NULL,
    _KEY VARCHAR(100) NOT NULL,
	VAL_REP BIGINT NOT NULL,
    VAL_SEQ BIGINT NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ, _KEY),
	CONSTRAINT `GRID_OBJ_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ) REFERENCES GRID_INDEX(SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) ON DELETE RESTRICT
);