CREATE TABLE IF NOT EXISTS GRID_CLOCK (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    REP BIGINT NOT NULL,
    SEQ BIGINT NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, REP, SEQ),
	CONSTRAINT `GRID_CLCK_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);