CREATE TABLE IF NOT EXISTS SEARCH_INDEX_STATUS (
	SEARCH_INDEX_ID BIGINT NOT NULL,
	STATE VARCHAR(50) NOT NULL DEFAULT 'CREATING',
	LAST_BUILD_ON TIMESTAMP(3) NULL,
	ERROR_MESSAGE VARCHAR(3000) DEFAULT NULL,
	APPLIED_CONFIGURATION JSON DEFAULT NULL,
	CHANGED_ON TIMESTAMP(3) NOT NULL,
	PRIMARY KEY (SEARCH_INDEX_ID),
	INDEX (STATE)
)