---
#
# This workflow runs the Synapse Stack Builder and then builds and runs the tests
# for the Synapse Repository Services.
#
# These parameters can be overridden with repo's action variables:
#
# - USER (the 'user' parameter for the Synapse build): defaults to repo' owner
# - STACK_BUILDER_REPO_OWNER: defaults to Sage-Bionetworks
# - STACK_BUILDER_BRANCH: defaults to develop
#
name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_and_test:
    permissions:
      # https://graphite.dev/guides/github-actions-permissions
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          # get the 'user' parameter, either from the repo' env or repo' owner if not set
          if [ ${{ vars.USER }} ]; then
            echo "user=${{ vars.USER }}" >> $GITHUB_ENV
          else
            echo "user=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          fi
          # capture the current branch as an environment variable
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          echo "stack_builder_branch=${{ vars.STACK_BUILDER_BRANCH }}" >> $GITHUB_ENV
          echo "stack_builder_repo_owner=${{ vars.STACK_BUILDER_REPO_OWNER }}" >> $GITHUB_ENV

      - id: oidc
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # TODO create a dedicated role
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1
          # eight hours
          role-duration-seconds: 28800
          output-credentials: true

      - name: checkout
        uses: actions/checkout@v5

      - name: Deploy CodePipeline to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        id: pipeline-deploy
        with:
          template: configuration/build/codepipeline_cf_template.yaml
          name: Synapse-Build-${{ env.user }}
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            SynapseBranch=${{ env.branch }},
            SynapseRepoOwner=${{ github.repository_owner }},
            GitHubToken=${{ secrets.GITHUB_TOKEN }},
            BuildParamUser=${{ env.user }},
            StackBuilderBranch=${{ env.stack_builder_branch }},
            StackBuilderRepoOwner=${{ env.stack_builder_repo_owner }}

      - name: Trigger CodePipeline
        run: |
          EXECUTION_ID=$(aws codepipeline start-pipeline-execution \
            --name ${{ steps.pipeline-deploy.outputs.PipelineName }} \
            --source-revisions actionName=CheckoutSynapseRepo,revisionType=COMMIT_ID,revisionValue=${{ github.sha }} \
            --variables name=AwsAccessKeyId,value=${{ steps.oidc.outputs.aws-access-key-id }} \
              name=AwsSecretAccessKey,value=${{ steps.oidc.outputs.aws-secret-access-key }} \
              name=AwsSessionToken,value=${{ steps.oidc.outputs.aws-session-token }}\
            --query 'pipelineExecutionId' --output text)

          echo "Pipeline execution ID: $EXECUTION_ID"
          echo "AWS Session Expiration: ${{ steps.oidc.outputs.aws-expiration }}"

          # Wait for completion
          FINAL_STAGE="BuildSynapseRepo"
          while true; do
            # this is a list of the statuses of all the stages that have started
            ALL_STAGE_STATUSES=$(aws codepipeline get-pipeline-state --name ${{ steps.pipeline-deploy.outputs.PipelineName }} \
              --query "stageStates[?(latestExecution.pipelineExecutionId=='$EXECUTION_ID')].latestExecution.status" --output text)
            # this is the status of just the final stage, or an empty sting if it hasn't started
            FINAL_STAGE_STATUS=$(aws codepipeline get-pipeline-state --name ${{ steps.pipeline-deploy.outputs.PipelineName }} \
              --query "stageStates[?(latestExecution.pipelineExecutionId=='$EXECUTION_ID' && stageName=='$FINAL_STAGE')].latestExecution.status" --output text)

            if [[ "$ALL_STAGE_STATUSES" =~ "Failed" || "$ALL_STAGE_STATUSES" =~ "Stopped" ]]; then
              # if there is a failure in any stage we stop
              echo "Pipeline execution $EXECUTION_ID finished with stage statuses: $ALL_STAGE_STATUSES"
              exit 1
            elif [[ "$FINAL_STAGE_STATUS" == "InProgress" || "$FINAL_STAGE_STATUS" == "" ]]; then
              # if the final stage hasn't started yet or is in progress, we continue
              echo "Pipeline execution $EXECUTION_ID is still in progress. Current status: $STATUS. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            elif [[ "$FINAL_STAGE_STATUS" == "Succeeded" ]]; then
              # if the final stage has succeeded then we're done
              echo "Pipeline execution $EXECUTION_ID succeeded."
              break
            else
              echo "Pipeline execution $EXECUTION_ID has unexpected status: $STATUS. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
             fi
          done
...
