name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_and_test:
    permissions:
      # https://graphite.dev/guides/github-actions-permissions
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{ env.user }} ]; then
            echo "user=${{ env.user }}" >> $GITHUB_ENV
          else
            echo "user=p3bhoff" >> $GITHUB_ENV
            # echo "user=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          fi
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # TODO we should create a role for dev' repo's to use
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1
          # eight hours
          role-duration-seconds: 28800

      - name: checkout
        uses: actions/checkout@v5

      - name: Deploy CodePipeline to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        id: pipeline-deploy
        with:
          # TODO give it a unique name
          name: CodePipeline
          template: configuration/build/codepipeline_cf_template.yaml
          parameter-overrides: >-
            SynapseBranch=${{ env.branch }},
            SynapseRepoOwner=${{ github.repository_owner }},
            GitHubToken=${{ secrets.GITHUB_TOKEN }},
            BuildParamUser=${{ env.user }}

      - name: Trigger CodePipeline
        run: |
          EXECUTION_ID=$(aws codepipeline start-pipeline-execution \
            --name ${{ steps.pipeline-deploy.outputs.PipelineName }} \
            --source-revisions actionName=CheckoutSynapseRepo,revisionType=COMMIT_ID,revisionValue=${{ github.sha }} \
            --query 'pipelineExecutionId' --output text)

          echo "Pipeline execution ID: $EXECUTION_ID"

          # Wait for completion
          while true; do
            STATUS=$(aws codepipeline get-pipeline-state --name ${{ steps.pipeline-deploy.outputs.PipelineName }} --query "stageStates[?latestExecution.pipelineExecutionId=='$EXECUTION_ID'].latestExecution.status" --output text | tr '\t' '\n' | sort | uniq)

            if [[ "$STATUS" == "Succeeded" ]]; then
              echo "Pipeline execution $EXECUTION_ID succeeded."
              break
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
              echo "Pipeline execution $EXECUTION_ID finished with status: $STATUS"
              exit 1
            else
              echo "Pipeline execution $EXECUTION_ID is still in progress. Current status: $STATUS. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            fi
          done

