---
#
# This workflow runs the Synapse Stack Builder and then builds and runs the tests
# for the Synapse Repository Services.
#
# These parameters can be overridden with repo's action variables:
#
# - USER (the 'user' parameter for the Synapse build): defaults to repo' owner
# - STACK_BUILDER_REPO_OWNER: defaults to Sage-Bionetworks
# - STACK_BUILDER_BRANCH: defaults to develop
#
name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_and_test:
    permissions:
      # https://graphite.dev/guides/github-actions-permissions
      id-token: write
      contents: read
      deployments: write
      security-events: write
      statuses: write
      actions: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          # get the 'user' parameter, either from the repo' env or repo' owner if not set
          if [ ${{ vars.USER }} ]; then
            echo "user=${{ vars.USER }}" >> $GITHUB_ENV
          elif
            echo "user=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          fi
          # capture the current branch as an environment variable
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
          echo "stack_builder_branch=${{ vars.STACK_BUILDER_BRANCH }}" >> $GITHUB_ENV
          echo "stack_builder_repo_owner=${{ vars.STACK_BUILDER_REPO_OWNER }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # TODO create a dedicated role
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1
          # eight hours
          role-duration-seconds: 28800

      - name: checkout
        uses: actions/checkout@v5

      - name: Deploy CodePipeline to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        id: pipeline-deploy
        with:
          template: configuration/build/codepipeline_cf_template.yaml
          name: Synapse-Build-${{ env.user }}
          parameter-overrides: >-
            SynapseBranch=${{ env.branch }},
            SynapseRepoOwner=${{ github.repository_owner }},
            GitHubToken=${{ secrets.GITHUB_TOKEN }},
            BuildParamUser=${{ env.user }},
            StackBuilderBranch=${{ env.stack_builder_branch }},
            StackBuilderRepoOwner=${{ env.stack_builder_repo_owner }}

      - name: Trigger CodePipeline
        run: |
          EXECUTION_ID=$(aws codepipeline start-pipeline-execution \
            --name ${{ steps.pipeline-deploy.outputs.PipelineName }} \
            --source-revisions actionName=CheckoutSynapseRepo,revisionType=COMMIT_ID,revisionValue=${{ github.sha }} \
            --query 'pipelineExecutionId' --output text)

          echo "Pipeline execution ID: $EXECUTION_ID"

          # Wait for completion
          while true; do
            STATUS=$(aws codepipeline get-pipeline-state --name ${{ steps.pipeline-deploy.outputs.PipelineName }} --query "stageStates[?latestExecution.pipelineExecutionId=='$EXECUTION_ID'].latestExecution.status" --output text | tr '\t' '\n' | sort | uniq)

            if [[ "$STATUS" == "Succeeded" ]]; then
              echo "Pipeline execution $EXECUTION_ID succeeded."
              break
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
              echo "Pipeline execution $EXECUTION_ID finished with status: $STATUS"
              exit 1
            else
              echo "Pipeline execution $EXECUTION_ID is still in progress. Current status: $STATUS. Waiting..."
              sleep 30 # Wait for 30 seconds before checking again
            fi
          done
...
