name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_and_test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{ env.user }} ]; then
            echo "user=${{ env.user }}" >> $GITHUB_ENV
          else
            echo "user=p3bhoff" >> $GITHUB_ENV
            # echo "user=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          fi

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # TODO I'm not really sure what this does.  Can we just use the service role created for the CodeBuild project?
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1

      - name: Build and Test
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: plfm9092
          buildspec-override: |
            version: 0.2
            env:
              variables:
                stack: dev
                org_sagebionetworks_repository_database_connection_url: dev-${{ env.user }}-db.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                org_sagebionetworks_table_cluster_endpoint_0: dev-${{ env.user }}-table-0.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                org_sagebionetworks_search_enabled: false
                org_sagebionetworks_cloudfront_domainname: data.dev.sagebase.org
                m2_cache_parent_folder: .
                src_folder: .
              secrets-manager:
                org_sagebionetworks_stackEncryptionKey: org.sagebionetworks.stackEncryptionKey
                rds_password: build.rds.password
                org_sagebionetworks_cloudfront_keypair: org.sagebionetworks.cloudfront.private.key.id
                org_sagebionetworks_cloudfront_private_key_secret: build.org.sagebionetworks.cloudfront.private.key.secret
            phases:
              install:
                commands:
                  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-install-cli.html
                  - echo "Installing MySQL CLI"
                  # - sudo dnf -y update && sudo dnf install -y mariadb105
              build:
                commands:
                  - ./docker_build.sh
                #- aws sts assume-role --role-arn arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev --role-session-name build-test
