
name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']


jobs:
  # this is necessary to make env values available to later jobs
  get-env:
    runs-on: ubuntu-latest
    steps:
       - run: |
           echo "INSTANCE=${{ env.INSTANCE }}" >> $GITHUB_ENV
           echo "STACK_BRANCH=${{ env.STACK_BRANCH }}" >> $GITHUB_ENV

  build_and_test:
    needs: get-env
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1
          
      - name: Build and Test
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: plfm9092 
          buildspec-override: |
            version: 0.2
            env:
              variables:
                INSTANCE: devp3bhoff
                user: devp3bhoff
                stack: dev
                # TODO: parameterized the next two lines:
                org_sagebionetworks_repository_database_connection_url: dev-p3bhoff-db.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                org_sagebionetworks_table_cluster_endpoint_0: dev-p3bhoff-table-0.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                STACK_BRANCH: develop
                org_sagebionetworks_search_enabled: false
                org_sagebionetworks_cloudfront_domainname: data.dev.sagebase.org
              secrets-manager:
                # TODO: Replace this keypair with OIDC auth':
                org_sagebionetworks_stack_iam_id: org.sagebionetworks.stack.iam.id.bhoff
                org_sagebionetworks_stack_iam_key: org.sagebionetworks.stack.iam.key.bhoff
                org_sagebionetworks_stackEncryptionKey: org.sagebionetworks.stackEncryptionKey
                rds_password: dev.org.sagebionetworks.repository.db.readonlypassword
                org_sagebionetworks_cloudfront_keypair: org.sagebionetworks.cloudfront.private.key.id
                org_sagebionetworks_cloudfront_private_key_secret: org.sagebionetworks.cloudfront.private.key.secret
            phases:
              install:
                commands:
                  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-install-cli.html
                  - echo "Installing MySQL CLI"
                  - sudo dnf -y update && sudo dnf install -y mariadb105
              build:
                commands:
                  - ./docker_build.sh
        env:
          m2_cache_parent_folder: .
        