name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_and_test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{ env.user }} ]; then
            echo "user=${{ env.user }}" >> $GITHUB_ENV
          else
            echo "user=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          fi
          if [ ${{ env.STACK_BRANCH }} ]; then
            echo "STACK_BRANCH=${{ env.STACK_BRANCH }}" >> $GITHUB_ENV
          else
            echo "STACK_BRANCH=develop" >> $GITHUB_ENV
          fi

      - name: Checkout StackBuilder repository
        uses: actions/checkout@v3
        with:
          repository: Sage-Bionetworks/Synapse-Stack-Builder
          ref: ${{ env.STACK_BRANCH }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
          aws-region: us-east-1

      - name: Compile and Run StackBuilder
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: plfm9092
          buildspec-override: |
            version: 0.2
            env:
              variables:
                user: ${{ env.user }}
            phases:
              build:
                commands:
                  - |
                    STS_CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::449435941126:role/synapse-dev-cmk-SynapseDeploymentRole-15QJA2H05YVY --role-session-name build-stack)
                    sudo yum install -y jq
                    export AWS_ACCESS_KEY_ID=$(echo $STS_CREDENTIALS | jq -r '.Credentials''.AccessKeyId')
                    export AWS_SECRET_ACCESS_KEY=$(echo $STS_CREDENTIALS | jq -r '.Credentials''.SecretAccessKey')
                    export AWS_SESSION_TOKEN=$(echo $STS_CREDENTIALS | jq -r '.Credentials''.SessionToken')
                    echo AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
                    echo AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
                    echo AWS_SESSION_TOKEN $AWS_SESSION_TOKEN
                    echo "let's try aws s3 ls:"
                    aws s3 ls
                    mvn clean install
                    export CMD_PROPS=\
                    " -DAWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID"\
                    " -DAWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY"\
                    " -DAWS_SESSION_TOKEN=AWS_SESSION_TOKEN"\
                    " -Dorg.sagebionetworks.stack=dev"\
                    " -Dorg.sagebionetworks.instance=$user"\
                    " -Dorg.sagebionetworks.vpc.subnet.color=Green"
                    java -Xms256m -Xmx2g -cp ./target/stack-builder-0.2.0-SNAPSHOT-jar-with-dependencies.jar \
                    $CMD_PROPS org.sagebionetworks.template.repo.RepositoryBuilderMain

      - name: Checkout Synapse-Repository-Services repository
        uses: actions/checkout@v3

#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev
#          aws-region: us-east-1

      - name: Build and Test
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: plfm9092
          buildspec-override: |
            version: 0.2
            env:
              variables:
                stack: dev
                org_sagebionetworks_repository_database_connection_url: dev-${{ env.user }}-db.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                org_sagebionetworks_table_cluster_endpoint_0: dev-${{ env.user }}-table-0.cdusmwdhqvso.us-east-1.rds.amazonaws.com
                STACK_BRANCH: ${{ env.STACK_BRANCH }}
                org_sagebionetworks_search_enabled: false
                org_sagebionetworks_cloudfront_domainname: data.dev.sagebase.org
                m2_cache_parent_folder: .
                src_folder: .
              secrets-manager:
                org_sagebionetworks_stackEncryptionKey: org.sagebionetworks.stackEncryptionKey
                rds_password: build.rds.password
                org_sagebionetworks_cloudfront_keypair: org.sagebionetworks.cloudfront.private.key.id
                org_sagebionetworks_cloudfront_private_key_secret: build.org.sagebionetworks.cloudfront.private.key.secret
            phases:
              install:
                commands:
                  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-install-cli.html
                  - echo "Installing MySQL CLI"
                  - sudo dnf -y update && sudo dnf install -y mariadb105
              build:
                commands:
                  - ./docker_build.sh
                #- aws sts assume-role --role-arn arn:aws:iam::449435941126:role/sagebase-github-oidc-sage-bionetworks-synapse-ops-dev --role-session-name build-test
